id: PEA7AD585
initial_creation_type: ocr
source_metadata:
  volumes:
    05389ad507e944fe91e66308fe6f46db:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: སྦྱིན་སྲེག་གི་ཆོ་ག།
      total_pages: 1734
      volume_number: 34
